#!/bin/sh
set -e
# Automatically added by dh_installdocs
if [ "$1" = configure ] && which install-docs >/dev/null 2>&1; then
	install-docs -i /usr/share/doc-base/aras
fi
# End automatically added section
chmod 666 /var/log/aras/*
